name: drw
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2 #開啟手機相簿
  intl: ^0.20.2 #格式化日期
  fluttertoast: ^8.2.12 #顯示警告訊息
  flutter_dash: ^1.0.0 #繪製底線
  provider: ^6.1.5 #類別狀態管理
  http: ^0.13.6 #發送http請求，用於對接伺服器
  path: ^1.9.0 #處理路徑字串，用於檔案儲存、上傳/下載檔案、解析路徑或檔名
  http_parser: ^4.0.2 #解析和格式化HTTP相關格式，例如:媒體(MediaType)
  camera: 0.10.5+9 #開啟手機相機
  image: ^4.5.4 #處理圖片
  dropdown_button2: ^2.3.9 #下拉式選單
  location: ^7.0.1 #定位使用者位置
  mime: ^2.0.0 #確定副檔名
  google_maps_flutter: ^2.10.1 #顯示google地圖
  google_maps_webservice: ^0.0.20-nullsafety.5  # Google Places & 距離計算
  flutter_dotenv: ^5.2.1 #使用.env檔案
  url_launcher: ^6.3.1 #跳轉至外部網站
  carousel_slider: ^5.1.1 #輪播圖片
  permission_handler: ^11.3.0 #權限請求
  file_picker: ^10.2.0 #另一種圖片選擇器
  fluentui_system_icons: ^1.1.273
  flutter_local_notifications: ^18.0.1 #提醒器
  timezone: ^0.9.4 #系統通知比對時間(取得時區)
  flutter_timezone: ^4.1.0 #系統通知比對時間(取得時區)
  shared_preferences: ^2.2.2
  geolocator: ^13.0.2 #取得地理位置
  geolocator_android: 4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  # flutter_dotenv: ^5.1.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/icon.png
    - images/line.png
    - images/hospital.png
    - images/cut.png
    - images/burn.png
    - images/bruise.png
    - images/register_icon.png
    - images/nurse_bear.png
    - images/new_photo_icon.png
    - images/old_photo_icon.png
    - images/doctor_bear.png
    - images/nursebear.png
    - images/gray_maker.png
    - images/red_maker.png
    - images/star_marker.png
    - images/cut1.png
    - images/cut2.png
    - images/cut3.png
    - images/cut4.png
    - images/cut5.png
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSansTC
      fonts:
        - asset: fonts/NotoSansTC-Bold.ttf
        - asset: fonts/NotoSansTC-Regular.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package



# 11146002↓
# name: drw
# description: "A new Flutter project."
# # The following line prevents the package from being accidentally published to
# # pub.dev using `flutter pub publish`. This is preferred for private packages.
# publish_to: 'none' 
# version: 1.0.0+1

# environment:
#   sdk: ^3.5.4

# # Dependencies specify other packages that your package needs in order to work.
# # To automatically upgrade your package dependencies to the latest versions
# # consider running `flutter pub upgrade --major-versions`. Alternatively,
# # dependencies can be manually updated by changing the version numbers below to
# # the latest version available on pub.dev. To see which dependencies have newer
# # versions available, run `flutter pub outdated`.
# dependencies:
#   flutter:
#     sdk: flutter


#   # The following adds the Cupertino Icons font to your application.
#   # Use with the CupertinoIcons class for iOS style icons.
#   cupertino_icons: ^1.0.8
#   image_picker: ^1.1.2 #開啟手機相簿
#   intl: ^0.20.2 #格式化日期
#   fluttertoast: ^8.2.12 #顯示警告訊息
#   flutter_dash: ^1.0.0 #繪製底線
#   provider: ^6.1.5 #類別狀態管理
#   http: ^0.13.6 #發送http請求，用於對接伺服器
#   path: ^1.9.0 #處理路徑字串，用於檔案儲存、上傳/下載檔案、解析路徑或檔名
#   http_parser: ^4.0.2 #解析和格式化HTTP相關格式，例如:媒體(MediaType)
#   camera: 0.10.5+9 #開啟手機相機
#   image: ^4.5.4 #處理圖片
#   dropdown_button2: ^2.3.9 #下拉式選單
#   location: ^7.0.1 #定位使用者位置
#   mime: ^2.0.0 #確定副檔名
#   google_maps_flutter: ^2.10.1 #顯示google地圖
# # 11146024 ↓↓↓ 11146017 ↓↓↓
#   #geolocator: ^10.1.0 #取得地理位置
# #11146002 ↓↓↓
#   geolocator: ^13.0.2 #取得地理位置
#   geolocator_android: 4.6.1

#   google_maps_webservice: ^0.0.20-nullsafety.5  # Google Places & 距離計算
#   flutter_dotenv: ^5.2.1 #使用.env檔案
#   url_launcher: ^6.3.1 #跳轉至外部網站
#   carousel_slider: ^5.1.1 #輪播圖片
#   permission_handler: ^11.3.0 #權限請求
#   file_picker: ^10.2.0 #另一種圖片選擇器

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

#   # The "flutter_lints" package below contains a set of recommended lints to
#   # encourage good coding practices. The lint set provided by the package is
#   # activated in the `analysis_options.yaml` file located at the root of your
#   # package. See that file for information about deactivating specific lint
#   # rules and activating additional ones.
#   flutter_lints: ^4.0.0

# # For information on the generic Dart part of this file, see the
# # following page: https://dart.dev/tools/pub/pubspec

# # The following section is specific to Flutter packages.
# flutter:

#   # The following line ensures that the Material Icons font is
#   # included with your application, so that you can use the icons in
#   # the material Icons class.
#   uses-material-design: true

#   # To add assets to your application, add an assets section, like this:
#   assets:
#     - images/icon.png
#     - images/line.png
#     - images/hospital.png
#     - images/cut.png
#     - images/burn.png
#     - images/bruise.png
#     - images/register_icon.png
#     - images/nurse_bear.png
#     - images/new_photo_icon.png
#     - images/old_photo_icon.png
#     - images/gray_maker.png
#     - images/doctor_bear.png
#     - .env

#   # An image asset can refer to one or more resolution-specific "variants", see
#   # https://flutter.dev/to/resolution-aware-images

#   # For details regarding adding assets from package dependencies, see
#   # https://flutter.dev/to/asset-from-package

#   # To add custom fonts to your application, add a fonts section here,
#   # in this "flutter" section. Each entry in this list should have a
#   # "family" key with the font family name, and a "fonts" key with a
#   # list giving the asset and other descriptors for the font. For
#   # example:
#   fonts:
#     - family: NotoSansTC
#       fonts:
#         - asset: fonts/NotoSansTC-Bold.ttf
#         - asset: fonts/NotoSansTC-Regular.ttf
#           weight: 700
#   #   - family: Trajan Pro
#   #     fonts:
#   #       - asset: fonts/TrajanPro.ttf
#   #       - asset: fonts/TrajanPro_Bold.ttf
#   #         weight: 700
#   #
#   # For details regarding fonts from package dependencies,
#   # see https://flutter.dev/to/font-from-package
