/// Flutter icons FontAwesome5
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FontAwesome5
///      fonts:
///       - asset: fonts/FontAwesome5.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FontAwesome5 {
  FontAwesome5._();

  static const _kFontFam = 'FontAwesome5';
  static const String? _kFontPkg = null;

  static const IconData facebook_square = IconData(0xf082, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_plus_square = IconData(0xf0d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line = IconData(0xf3c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
